[package]
name = "cracking_the_job_interview"
version = "0.1.0"
authors = ["oren <oren@cynerio.co>"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
itertools = "0.9.0"